### ISSUE TITLE
Python module change

### ISSUE THREAD

**Issue by ChiralMedia** [basho-labs/riak-mesos-tools#16]
Mesos 0.28.1, DC/OS 1.7  Riak framework 0.1.1

dcos_riak/cli.py contains a reference to util.get_config() that is now config.get_config()

Example:

u1@bootstrapper ~]$ dcos riak cluster list --debug
[DEBUG]Framework: riak[/DEBUG]
[DEBUG]Cluster: riak-cluster[/DEBUG]
[DEBUG]Zookeeper: master.mesos:2181[/DEBUG]
[DEBUG]Public DNS: {{public.dns}}[/DEBUG]
[DEBUG]Nodes: 1[/DEBUG]
[DEBUG]Command: cluster list[/DEBUG]
Traceback (most recent call last):
  File "/home/u1/.dcos/subcommands/riak/env/bin/dcos-riak", line 11, in <module>
    sys.exit(main())
  File "/home/u1/.dcos/subcommands/riak/env/lib/python2.7/site-packages/dcos_riak/cli.py", line 304, in main
    return run(args)
  File "/home/u1/.dcos/subcommands/riak/env/lib/python2.7/site-packages/dcos_riak/cli.py", line 224, in run
    service_url = api_url(framework) + "api/v1/"
  File "/home/u1/.dcos/subcommands/riak/env/lib/python2.7/site-packages/dcos_riak/cli.py", line 64, in api_url
    base_url = util.get_config().get('core.dcos_url').rstrip("/")
AttributeError: 'module' object has no attribute 'get_config'
[u1@bootstrapper ~]$

**Comment by sanmiguel** [comment]
As per #24, this is a symptom of using the older framework, fixed by using v1.0.0+

If that's not the case, please feel free to re-open this issue.
