### ISSUE TITLE
exception in `riak-mesos framework install`

### ISSUE THREAD

**Issue by seanjensengrey** [basho-labs/riak-mesos-tools#47]
exception in `riak-mesos framework install`
## mesos 1.0.0 on Ubuntu 14

installed tools via

`pip install -U git+https://github.com/basho-labs/riak-mesos-tools@1.3.0`

config https://gist.github.com/6dd7e804c65d0e8dc187ffd9799996cd
# pip list

```
$ pip list
click (6.6)
dcos (0.4.10)
docopt (0.6.2)
futures (3.0.5)
gitdb (0.6.4)
GitPython (1.0.2)
jsonschema (2.4.0)
kazoo (2.2.1)
pager (3.3)
pip (8.1.2)
portalocker (0.5.7)
prettytable (0.7.2)
Pygments (2.1.3)
pypng (0.0.18)
pystache (0.5.4)
requests (2.11.1)
riak-mesos (1.3.0)
setuptools (26.0.0)
six (1.10.0)
smmap (0.9.0)
toml (0.9.2)
wheel (0.29.0)
```
# exception

```
Insecure SSL Mode: False
Verbose Mode: True
Debug Mode: True
JSON Mode: False
Using config file: /Users/basho/.config/riak-mesos/config.json
Defaulting to configuration based URLs
INFO:dcos.http:Sending HTTP ['get'] to ['http://marathon.mesos:8080/ping']: {'Accept': 'application/json'}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): marathon.mesos
DEBUG:requests.packages.urllib3.connectionpool:"GET /ping HTTP/1.1" 200 5
INFO:dcos.http:Received HTTP response [200]: {'X-Marathon-Leader': 'http://10.1.11.110:8080', 'Content-Type': 'text/plain;charset=iso-8859-1', 'Cache-Control': 'must-revalidate,no-cache,no-store', 'Expires': '0', 'Date': 'Fri, 26 Aug 2016 18:36:17 GMT', 'Content-Length': '5', 'Access-Control-Allow-Credentials': 'true', 'Server': 'Jetty(9.3.z-SNAPSHOT)', 'Pragma': 'no-cache'}
DEBUG:dcos.util:duration: dcos.http._request: 0.10s
HTTP URL: http://marathon.mesos:8080/ping
HTTP Method: GET
HTTP Body: None
HTTP Status: 200
HTTP Response Text: pong

Setting marathon URL to http://marathon.mesos:8080/
INFO:dcos.http:Sending HTTP ['post'] to ['http://marathon.mesos:8080/v2/apps']: {'Accept': 'application/json'}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): marathon.mesos
DEBUG:requests.packages.urllib3.connectionpool:"POST /v2/apps HTTP/1.1" 422 None
INFO:dcos.http:Received HTTP response [422]: {'X-Marathon-Leader': 'http://10.1.11.110:8080', 'Content-Type': 'application/json; qs=2', 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Expires': '0', 'Date': 'Fri, 26 Aug 2016 18:36:17 GMT', 'Transfer-Encoding': 'chunked', 'Server': 'Jetty(9.3.z-SNAPSHOT)', 'Pragma': 'no-cache'}
DEBUG:dcos.util:duration: dcos.http._request: 0.08s
Traceback (most recent call last):
  File "/Users/basho/work/rmf-closing-aug25/rmf.env/lib/python3.5/site-packages/dcos/marathon.py", line 120, in _http_req
    return fn(*args, **kwargs)
  File "/Users/basho/work/rmf-closing-aug25/rmf.env/lib/python3.5/site-packages/dcos/http.py", line 281, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Users/basho/work/rmf-closing-aug25/rmf.env/lib/python3.5/site-packages/dcos/http.py", line 235, in request
    raise DCOSHTTPException(response)
dcos.errors.DCOSHTTPException: Error while fetching [http://marathon.mesos:8080/v2/apps]: HTTP 422: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/basho/work/rmf-closing-aug25/rmf.env/bin/riak-mesos", line 11, in <module>
    load_entry_point('riak-mesos==1.3.0', 'console_scripts', 'riak-mesos')()
  File "/Users/basho/work/rmf-closing-aug25/rmf.env/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/basho/work/rmf-closing-aug25/rmf.env/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/basho/work/rmf-closing-aug25/rmf.env/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/basho/work/rmf-closing-aug25/rmf.env/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/basho/work/rmf-closing-aug25/rmf.env/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/basho/work/rmf-closing-aug25/rmf.env/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/basho/work/rmf-closing-aug25/rmf.env/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/basho/work/rmf-closing-aug25/rmf.env/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/basho/work/rmf-closing-aug25/rmf.env/lib/python3.5/site-packages/riak_mesos/commands/cmd_framework.py", line 57, in install
    client.add_app(framework_json)
  File "/Users/basho/work/rmf-closing-aug25/rmf.env/lib/python3.5/site-packages/dcos/marathon.py", line 290, in add_app
    timeout=self._timeout)
  File "/Users/basho/work/rmf-closing-aug25/rmf.env/lib/python3.5/site-packages/dcos/marathon.py", line 122, in _http_req
    raise _to_exception(e.response)
dcos.errors.DCOSException: Error: Object is not valid
```

**Comment by seanjensengrey** [comment]
I failed to set the `config.json` value for the riak_url. 

```
'RIAK_MESOS_RIAK_PKG': '${riakUrl}',
```

 So maybe we need more validation on the config itself.
